<a href="https://colab.research.google.com/github/rosangithub/ML/blob/main/kfold_coss_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
digits=load_digits()

In [6]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
df=pd.DataFrame(digits.data)

In [10]:
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [12]:
X=df


In [13]:
X

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [14]:
y=digits.target

In [15]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [32]:
X_train

0    1     2     3     4     5     6    7    8    9   ...    54   55  \
807   0.0  0.0   2.0  10.0  10.0  11.0   0.0  0.0  0.0  0.0  ...   1.0  0.0   
290   0.0  0.0   0.0   8.0  15.0   2.0   0.0  0.0  0.0  0.0  ...  13.0  0.0   
205   0.0  0.0   3.0  13.0  12.0   2.0   0.0  0.0  0.0  0.0  ...   1.0  0.0   
693   0.0  0.0   1.0  10.0  15.0  11.0   7.0  0.0  0.0  0.0  ...   0.0  0.0   
962   0.0  0.0   8.0  12.0  13.0   5.0   0.0  0.0  0.0  4.0  ...   3.0  0.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...  ...  ...   ...  ...   
1720  0.0  0.0   6.0  14.0   9.0   5.0   2.0  0.0  0.0  7.0  ...   0.0  0.0   
466   0.0  0.0   0.0   5.0  16.0   9.0   0.0  0.0  0.0  0.0  ...   0.0  0.0   
1230  0.0  0.0   9.0  16.0  16.0   7.0   0.0  0.0  0.0  2.0  ...   1.0  0.0   
853   0.0  4.0  16.0  15.0   1.0   0.0   0.0  0.0  0.0  6.0  ...   5.0  0.0   
1046  0.0  0.0   3.0  15.0  16.0  16.0  12.0  0.0  0.0  0.0  ...   0.0  0.0   

       56   57    58    59    60    61   62   63  
807   0.0  0.0   2.0  14.0  16.0  13.0  0.0  0.0  
290   0.0  0.0   0.0   9.0  16.0  13.0  5.0  0.0  
205   0.0  0.0   3.0  16.0  11.0   8.0  0.0  0.0  
693   0.0  0.0   3.0  12.0  16.0   2.0  0.0  0.0  
962   0.0  0.0  10.0  16.0  16.0   6.0  0.0  0.0  
...   ...  ...   ...   ...   ...   ...  ...  ...  
1720  0.0  0.0   5.0  14.0  11.0   3.0  0.0  0.0  
466   0.0  0.0   0.0   5.0  14.0   9.0  0.0  0.0  
1230  0.0  0.0  11.0  15.0  15.0   6.0  0.0  0.0  
853   0.0  3.0  16.0  16.0  16.0  16.0  8.0  0.0  
1046  0.0  0.0   3.0  16.0   2.0   0.0  0.0  0.0  

[1257 rows x 64 columns]

In [33]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
print("model trained successfull")
lr.score(X_test,y_test)

model trained successfull


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [34]:
svm=SVC()
svm.fit(X_train,y_train)
print('model trainded successfully')

model trainded successfully


In [35]:
svm.score(X_test,y_test)

0.9796296296296296

In [36]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9537037037037037

In [44]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [45]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [46]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [47]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)


In [48]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [49]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9796296296296296

In [68]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [69]:
scores_lr=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_lr.append( get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=42),X_train,X_test,y_train,y_test))

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [70]:
scores_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [71]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [72]:
scores_rf

[0.9282136894824707, 0.9482470784641068, 0.9181969949916527]

In [73]:
from sklearn.model_selection import cross_val_score

In [74]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [75]:
cross_val_score(SVC(),X,y)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [79]:
cross_val_score(RandomForestClassifier(n_estimators=55),X,y)

array([0.93611111, 0.92222222, 0.94986072, 0.97493036, 0.92200557])